# Generated by Marten 0.6.3 on 2026-05-08 00:10:54 +02:00

class Migration::Books::V202605080010541 < Marten::Migration
  def plan
    create_table :books_section do
      column :id, :big_int, primary_key: true, auto: true
      column :body, :text, null: true
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :books_picture do
      column :id, :big_int, primary_key: true, auto: true
      column :caption, :string, max_size: 1024, null: true
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :books_page do
      column :id, :big_int, primary_key: true, auto: true
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :books_markdown do
      column :id, :big_int, primary_key: true, auto: true
      column :record_type, :string, max_size: 255, null: true
      column :record_id, :big_int, null: true
      column :name, :string, max_size: 64
      column :content, :text, default: ""
      column :created_at, :date_time
      column :updated_at, :date_time
    
      index :markdown_record_idx, [:record_type, :record_id, :name]
    end

    create_table :books_leaf do
      column :id, :big_int, primary_key: true, auto: true
      column :leafable_type, :string, max_size: 255, null: true
      column :leafable_id, :big_int, null: true
      column :position_score, :float, default: 0.0
      column :status, :string, max_size: 16, default: "active"
      column :title, :string, max_size: 255
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :books_book do
      column :id, :big_int, primary_key: true, auto: true
      column :title, :string, max_size: 255
      column :subtitle, :string, max_size: 255, null: true
      column :author, :string, max_size: 255, null: true
      column :published, :bool, default: false
      column :slug, :string, max_size: 255
      column :theme, :string, max_size: 32, default: "blue"
      column :everyone_access, :bool, default: false
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :books_attachment do
      column :id, :big_int, primary_key: true, auto: true
      column :record_type, :string, max_size: 255, null: true
      column :record_id, :big_int, null: true
      column :name, :string, max_size: 64
      column :file, :string, max_size: 100
      column :variant_of_id, :reference, to_table: :books_attachment, to_column: :id, null: true
      column :variation_kind, :string, max_size: 64, null: true
      column :content_type, :string, max_size: 128, null: true
      column :byte_size, :big_int, null: true
      column :slug, :string, max_size: 255, null: true, unique: true
      column :created_at, :date_time
      column :updated_at, :date_time
    
      index :attachment_record_idx, [:record_type, :record_id, :name]
    end

    create_table :books_edit do
      column :id, :big_int, primary_key: true, auto: true
      column :leafable_type, :string, max_size: 255, null: true
      column :leafable_id, :big_int, null: true
      column :event, :string, max_size: 16
      column :created_at, :date_time
      column :updated_at, :date_time
      column :leaf_id, :reference, to_table: :books_leaf, to_column: :id
    end

    add_column :books_leaf, :book_id, :reference, to_table: :books_book, to_column: :id

    add_index :books_edit, :edit_leaf_idx, [:leaf_id, :created_at]

    add_index :books_leaf, :leaf_book_status_idx, [:book_id, :status]
  end
end
