# Generated by Marten 0.6.3 on 2026-05-08 00:10:54 +02:00

class Migration::Accounts::V202605080010541 < Marten::Migration
  depends_on :books, "202605080010541_auto"

  def plan
    create_table :accounts_user do
      column :id, :big_int, primary_key: true, auto: true
      column :email, :string, max_size: 254, unique: true
      column :password, :string, max_size: 128
      column :created_at, :date_time
      column :updated_at, :date_time
      column :name, :string, max_size: 255
      column :role, :string, max_size: 32, default: "member"
      column :active, :bool, default: true
    end

    create_table :accounts_account do
      column :id, :big_int, primary_key: true, auto: true
      column :name, :string, max_size: 255
      column :join_code, :string, max_size: 64
      column :custom_styles, :text, null: true
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :accounts_access do
      column :id, :big_int, primary_key: true, auto: true
      column :level, :string, max_size: 16
      column :created_at, :date_time
      column :updated_at, :date_time
      column :user_id, :reference, to_table: :accounts_user, to_column: :id
      column :book_id, :reference, to_table: :books_book, to_column: :id
    end

    add_unique_constraint :accounts_access, :access_user_book_unique, [:user_id, :book_id]

    add_index :accounts_access, :access_book_idx, [:book_id]
  end
end
